### ISSUE TITLE
Hangs up when saving as a tape .mtx file

### ISSUE THREAD

**Issue by Ardeer** [Memotech-Bill/MEMU#2]
Bill,

used the sysrq button to select the tape wav file to be loaded and specified what the subsequent saved .mtx filename would be.
LOAD "" loaded the wav file and when listed the code was displayed.
Saving the file caused the emulator to hang? It did start to save the file as there is something saved in the folder. Any thoughts?

thanks.

**Comment by Memotech-Bill** [comment]
Working on it.

**Comment by Memotech-Bill** [comment]
Committed fixes to a couple of issues. However I am not sure I have seen what you describe.

You should not need to erase the MEMU folder and start again. Instead, from inside the MEMU folder do `git pull`. Then, in your build folder do `make`.

If you still have issues, please itemise all the steps you are taking.

If you are trying to recover code from old audio tapes, you might be interested in [TapeView](http://www.mtxworld.dk/memorum/viewtopic.php?p=3739#p3739)

**Comment by Ardeer** [comment]
Bill,

What ever changes you made, appear to have worked as I can now save the file as a *.mtx file. Many thanks.

I don't need TapeView as I have my own python code to convert *.mtx file to a text listing.

regards,
