### ISSUE TITLE
does not compile on raspbian armhf or aarch64 bookworm

### ISSUE THREAD

**Issue by gilmod714** [Memotech-Bill/MEMU#4]
does not compile on raspbian OS armhf or aarch64 (bookworm latest stock images) from pi imager

config.txt modified for fkms, cmake installed ..

cmake spits out an error about "structure no found or something" for mfx..

something's missing in the package ?!

**Comment by Memotech-Bill** [comment]
Which build target are you using: `cmake -DTARGET=XWin ..` or `cmake -DTARGET=RPi  ..` ?

As noted in the documentation the special features of the `RPi` build (GPU use and GPIO hardware interfacing) are not supported with recent RPi hardware or OS.

As a pure software emulation, the `XWin` target works well on RPi, the `RPi` build was only needed if you wished to attach retro-hardware.

In testing, I found that my experimental revisions for SDL build had broken the XWin build. Fixed with latest commits.

**Comment by gilmod714** [comment]
no matter which version I try , it gives the same error ..

I tried compiling build:  cmake -DTARGET=RPi .. which gave that error ..

then tried the XWin build .. same error , 

Will attach a screenshot later when I get a chance .. I'm not by my pi right now :)

**Comment by Memotech-Bill** [comment]
As said, testing did find a few errors introduced by SDL commits. Fixed these with some new commits. You will need to do `git pull` to update files.

**Comment by gilmod714** [comment]
Awesome, will try it .. thanks Bill 

unrelated suggestions ..
(1)  would it be possible to have the baremetal verison (runtime) not to EXIT to the shell-eventually with "EXIT" ?!  I think that would make it a more authentic experience having memu as *almost* a real hardware on pi ;)

(2) is there a way to have the "baremetal" run in full-screen mode with correct aspect-ratio ?! .. i tried the multiple -vid-win-big in config files here and there and in confix.txt various resolutions.. no dice



EDIT:

both RPi and Xwin compiles OK now .. the "Baremetal" gives an error though, is it possible to include "Circle" compile & configure instructions here ?!

![IMG_20240423_183411](https://github.com/Memotech-Bill/MEMU/assets/163355639/29011e40-f087-4e62-961b-b096d01ca9a3)


![xwin](https://github.com/Memotech-Bill/MEMU/assets/163355639/d5c33df0-bcc3-4c60-afed-789f876fcaf0)

![rpi4](https://github.com/Memotech-Bill/MEMU/assets/163355639/47094fc3-b83b-4cda-abf7-3fb577a86fe6)

![memu](https://github.com/Memotech-Bill/MEMU/assets/163355639/6aa0bfbe-54ca-43ae-a2fa-3aa18ed14584)

**Comment by Memotech-Bill** [comment]
> (2) is there a way to have the "baremetal" run in full-screen mode with correct aspect-ratio ?! .. i tried the multiple -vid-win-big in config files here and there and in confix.txt various resolutions.. no dice

The following build targets did all run full-screen (and ignore -vid-win-big). However I am not sure whether any of them work on recent RPi & OS:

* TARGET=Fbuf. I don't know whether this will work with recent versions of RPi OS, and not in a position to conveniently test. Use a Lite version of the OS (No GUI). However, worth a try. May well need **fkms**.
* TARGET=RPi. This used GPU DISPMANX routines to scale up the display to full screen. But DISPMANX is not supported on recent RPi OS,
* TARGET=Circle. Bare metal screen access. Again probably not working on recent RPi.

**Comment by gilmod714** [comment]
Awesome! .. Thanks Bill .. I'm using a Pi4 right now.. I will test on other models as well and see how it goes .. I have  pi's 0,2,3,4 ..
Also noticed when running Alpha.com or any game (in cpm color) .. the game starts, but it is in the background of the frontend .. you can see it only when you exit-out ..  probably an SDL overlay issues ?!

**Comment by Memotech-Bill** [comment]
> Awesome! .. Thanks Bill .. I'm using a Pi4 right now.. I will test on other models as well and see how it goes .. I have pi's 0,2,3,4 .. Also noticed when running Alpha.com or any game (in cpm color) .. the game starts, but it is in the background of the frontend .. you can see it only when you exit-out .. probably an SDL overlay issues ?!

Which version are you talking about? With the XWin version, the CP/M text and the game are in different windows. You just have to switch to the other window.

For FBuf, only one screen can be displayed at a time. Use <Ctrl+F1>, <Ctrl+F2>, etc to select the different screens. The emulator cannot know which screen you want to look at.

**Comment by gilmod714** [comment]
both memu-fb and memu-pi do this actually .. 
but yeah, (ctrl+f1, f2) switches the screen .. I see that now ..
