### ISSUE TITLE
When running on a raspberry pi pico, WAV files do not load

### ISSUE THREAD

**Issue by elapt1c** [Memotech-Bill/MEMU#5]
memu: Failed to open input tape file

wav files that normally work for people don't work here and i can play them on my pc so they arent corrupt. i have audio tape on in the menu too.

**Comment by Memotech-Bill** [comment]
Finally found the time to look at this.

**tape.c** was missing the special version of **stdio.h** required for Pico. Fixed in latest commit.

**Comment by elapt1c** [comment]
that fixed it! thanks!
