### ISSUE TITLE
confusion about cp/m programs on SDX rpi pico

### ISSUE THREAD

**Issue by elapt1c** [Memotech-Bill/MEMU#6]
How am i supposed to run and load cp/m programs in the SDX mode of the rpi pico version of memu (which i have grown to love) such as hextrain? i selected the "games" rom as B and ran "USER DIR" and saw all the games listed. i dont know where to go from here. i have tried "USER LOAD HEXTRAIN.COM" but after a few seconds it returns "No data"

**Comment by Memotech-Bill** [comment]
They are CP/M programs. You have to start them from CP/M mode. Once started most of them use the VDP display. Use Ctrl+FN_key to switch between the different display modes.

**Comment by elapt1c** [comment]
when i press + (shift equals key) nothing happens is there a difference
like how qotes are shift+2?

**Comment by elapt1c** [comment]
nvm i read the docs it was ctrl+f1
