### ISSUE TITLE
hextrain broken

### ISSUE THREAD

**Issue by elapt1c** [Memotech-Bill/MEMU#7]
hextrain doesn't work. i will give the error message in a while cuz im busy right now

**Comment by elapt1c** [comment]
it says 
**HEX-TRAIN**
DSK INIT FAILED

**Comment by Memotech-Bill** [comment]
That version of hextrain should not have been included on the disk.

To run any version of hextrain you need the 202MB **ht.bin** file.

Then if running MEMU on a desktop machine, you need a copy of **htsi.com**. Mount the **ht.bin** file as a huge, read-only silicon disc.

If running MEMU on a Pico, then you need **htes.com**. The **ht.bin** file needs to copied onto the SD Card, starting at an offset of 64MB from the start.

These files can be downloaded from http://www.primrosebank.net/computers/mtx/projects/mfx/mfx_fw.htm

**Comment by elapt1c** [comment]
how do i do any of this? how do i even load .com files onto it and what does the 64 mb thing mean?

**Comment by Memotech-Bill** [comment]
Perhaps the simplest solution is to download the MFX disc image from http://www.primrosebank.net/computers/mtx/projects/mfx/mfx_usage.htm, near the bottom of the page,

Once downloaded, use **dd** to copy it onto an SD card. Overwrite the entire card, not just the FAT partition. Note that this will destroy any existing data on the card.

Hextrain uses a data file that is far too large for CP/M. It therefore accesses the storage media directly, reading from a location beyond the end of the CP/M disk images. Andy Key's site giving details appears to be down, but I have found a copy on the Wayback machine at https://web.archive.org/web/20230527071725/http://www.nyangau.org/hextrain/hextrain.htm

**Comment by elapt1c** [comment]
if i overwrite the whole sd card, the mtx software wont work, right?

**Comment by Memotech-Bill** [comment]
The MFX SD Card image includes multiple CP/M disk images containing many games as well as the Hextrain binary data file at the end of the image. It will work with any of the emulation modes supporting disk drives (SFX, CP/M or MFX).

As noted on the page, Dave provides a spreadsheet listing all the contents.

**Comment by elapt1c** [comment]
i don't feel like going through that trouble. will you fix the issue in the next update possibly?

**Comment by Memotech-Bill** [comment]
I have resolved the issue by removing the spurious copy of Hextrain from the floppy disk image.

This repository is for the MEMU emulator. It is never intended to be a definitive collection of Memotech games. Those are available from other sources.
